<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Respawn" Version="6.2.1" />
    <PackageReference Include="Testcontainers" Version="4.8.1" />
    <PackageReference Include="Testcontainers.MsSql" Version="4.8.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\CleanArchitecture.Cmms.Api.Assets\CleanArchitecture.Cmms.Api.Assets.csproj" />
    <ProjectReference Include="..\..\CleanArchitecture.Cmms.Application.Assets\CleanArchitecture.Cmms.Application.Assets.csproj" />
    <ProjectReference Include="..\..\CleanArchitecture.Cmms.Infrastructure.Assets\CleanArchitecture.Cmms.Infrastructure.Assets.csproj" />
    <ProjectReference Include="..\..\..\..\outbox\CleanArchitecture.Outbox\CleanArchitecture.Outbox.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>

