<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="Mohd2sh.CleanArchitecture.Core.Application" Version="2.0.1" />
    <PackageReference Include="Mohd2sh.CleanArchitecture.Outbox.Abstractions" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Contracts\CleanArchitecture.Cmms.Contracts.csproj" />
    <ProjectReference Include="..\..\..\core\CleanArchitecture.Core.Application.Pipelines\CleanArchitecture.Core.Application.Pipelines.csproj" />
    <ProjectReference Include="..\..\..\outbox\CleanArchitecture.Outbox.MassTransit.Bridge\CleanArchitecture.Outbox.MassTransit.Bridge.csproj" />
    <ProjectReference Include="..\CleanArchitecture.Cmms.Domain.Technicians\CleanArchitecture.Cmms.Domain.Technicians.csproj" />
  </ItemGroup>

</Project>


